/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Credit risk specific colors
        risk: {
          low: '#10b981',
          medium: '#f59e0b',
          high: '#ef4444',
          critical: '#7c2d12',
        },
        // Brand colors updated to match Stitch primary Indigo (#6366f1) and Navy
        primary: {
          50: '#f5f3ff',
          100: '#e0e2ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#1e1b4b',
          950: '#0f0e36',
          DEFAULT: '#6366f1',
        },
        // Override blue to match Indigo as well
        blue: {
          50: '#f5f3ff',
          100: '#e0e2ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#1e1b4b',
          950: '#0f0e36',
          DEFAULT: '#6366f1',
        },
        // Stitch design system custom properties
        "primary-fixed": "#e0e2ff",
        "error-container": "#fee2e2",
        "surface-bright": "#edeef4",
        "surface-variant": "#dcdee4",
        "on-error-container": "#991b1b",
        "on-error": "#ffffff",
        "surface-container": "#e2e4ea",
        "surface-container-lowest": "#f0f2f8",
        "on-secondary-fixed-variant": "#404252",
        "on-tertiary-fixed-variant": "#5b21b6",
        "on-secondary-container": "#585a68",
        "inverse-on-surface": "#e8eaf0",
        "tertiary-fixed-dim": "#c4b5fd",
        "secondary": "#6c6e7e",
        "secondary-fixed": "#d8dae6",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d4d6dc",
        "on-tertiary-container": "#3b1f63",
        "inverse-surface": "#2e3040",
        "secondary-fixed-dim": "#b8baca",
        "on-surface-variant": "#585a68",
        "background": "#e8eaf0",
        "on-secondary-fixed": "#1a1b26",
        "outline-variant": "#d0d2dc",
        "surface-container-highest": "#d6d8de",
        "on-tertiary-fixed": "#2e1065",
        "on-surface": "#2e3040",
        "primary-container": "#818cf8",
        "error": "#dc2626",
        "on-primary-fixed": "#1e1b4b",
        "secondary-container": "#d8dae6",
        "surface-tint": "#6366f1",
        "tertiary-fixed": "#ede9fe",
        "surface": "#e8eaf0",
        "outline": "#8a8c9a",
        "surface-container-low": "#e5e7ed",
        "on-primary-container": "#e0e2ff",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#4338ca",
        "tertiary": "#7c3aed",
        "on-secondary": "#ffffff",
        "on-background": "#2e3040",
        "surface-container-high": "#dcdee4",
        "tertiary-container": "#a78bfa",
        "primary-fixed-dim": "#a5b4fc",
        "inverse-primary": "#a5b4fc"
      },
      spacing: {
        '128': '32rem',
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "2xl": "48px",
        "3xl": "64px",
        "gutter": "16px",
        "container-margin": "24px",
        "base": "8px",
      },
      borderRadius: {
        'xl': '1rem',
      },
      fontFamily: {
        sans: ['Archivo', '"Archivo Fallback"', 'system-ui', 'sans-serif'],
        headline: ['Archivo', '"Archivo Fallback"', 'sans-serif'],
        display: ['Archivo', '"Archivo Fallback"', 'sans-serif'],
        body: ['Archivo', '"Archivo Fallback"', 'sans-serif'],
        label: ['Archivo', '"Archivo Fallback"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        "label-md": ['Archivo', '"Archivo Fallback"', "sans-serif"],
        "h1": ['Archivo', '"Archivo Fallback"', "sans-serif"],
        "body-md": ['Archivo', '"Archivo Fallback"', "sans-serif"],
        "h3": ['Archivo', '"Archivo Fallback"', "sans-serif"],
        "h2": ['Archivo', '"Archivo Fallback"', "sans-serif"],
        "h1-mobile": ['Archivo', '"Archivo Fallback"', "sans-serif"],
        "body-sm": ['Archivo', '"Archivo Fallback"', "sans-serif"],
        "body-lg": ['Archivo', '"Archivo Fallback"', "sans-serif"],
        "label-sm": ['Archivo', '"Archivo Fallback"', "sans-serif"],
        "h4": ['Archivo', '"Archivo Fallback"', "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "h1": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "h3": ["24px", { "lineHeight": "32px", "letterSpacing": "0em", "fontWeight": "600" }],
        "h2": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "h1-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "h4": ["20px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "600" }]
      },
      typography: {
        DEFAULT: {
          css: {
            color: '#1f2937',
            h1: {
              color: '#111827',
              fontWeight: '700',
            },
            h2: {
              color: '#111827',
              fontWeight: '600',
            },
            h3: {
              color: '#111827',
              fontWeight: '600',
            },
            strong: {
              color: '#111827',
              fontWeight: '600',
            },
            code: {
              color: '#dc2626',
              backgroundColor: '#f9fafb',
              padding: '0.25rem 0.5rem',
              borderRadius: '0.25rem',
            },
          },
        },
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideOut: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.3s ease-in',
        slideIn: 'slideIn 0.3s ease-out',
        slideOut: 'slideOut 0.3s ease-in',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      screens: {
        'xs': '320px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-green-100',
    'bg-yellow-100',
    'bg-red-100',
    'bg-blue-100',
    'text-green-800',
    'text-yellow-800',
    'text-red-800',
    'text-blue-800',
    'border-green-200',
    'border-yellow-200',
    'border-red-200',
    'border-blue-200',
  ],
}
